import { ICountry } from "../interfaces";

export const countries: ICountry[] = [
    {
        countryCode: "IN",
        countryName: "India",
        callingCode: "+91",
        continent: "Asia",
        currency: "INR",
        capital: "New Delhi",
        latitude: 20.5937,
        longitude: 78.9629,
        iso3: "IND"
    },
    {
        countryCode: "US",
        countryName: "USA",
        callingCode: "+1",
        continent: "Americas",
        currency: "USD",
        capital: "Washington, D.C.",
        latitude: 38.9072,
        longitude: -77.0369,
        iso3: "USA"
    },
    {
        countryCode: "RU",
        countryName: "Russia",
        callingCode: "+7",
        continent: "Europe/Asia",
        currency: "RUB",
        capital: "Moscow",
        latitude: 55.7558,
        longitude: 37.6176,
        iso3: "RUS"
    },
    {
        countryCode: "CN",
        countryName: "China",
        callingCode: "+86",
        continent: "Asia",
        currency: "CNY",
        capital: "Beijing",
        latitude: 39.9042,
        longitude: 116.4074,
        iso3: "CHN"
    },
    {
        countryCode: "JP",
        countryName: "Japan",
        callingCode: "+81",
        continent: "Asia",
        currency: "JPY",
        capital: "Tokyo",
        latitude: 35.6895,
        longitude: 139.6917,
        iso3: "JPN"
    },
    {
        countryCode: "KR",
        countryName: "South Korea",
        callingCode: "+82",
        continent: "Asia",
        currency: "KRW",
        capital: "Seoul",
        latitude: 37.5665,
        longitude: 126.9780,
        iso3: "KOR"
    },
    {
        countryCode: "AT",
        countryName: "Austria",
        callingCode: "+43",
        continent: "Europe",
        currency: "EUR",
        capital: "Vienna",
        latitude: 48.2082,
        longitude: 16.3738,
        iso3: "AUT"
    },
    {
        countryCode: "BE",
        countryName: "Belgium",
        callingCode: "+32",
        continent: "Europe",
        currency: "EUR",
        capital: "Brussels",
        latitude: 50.8503,
        longitude: 4.3517,
        iso3: "BEL"
    },
    {
        countryCode: "BG",
        countryName: "Bulgaria",
        callingCode: "+359",
        continent: "Europe",
        currency: "BGN",
        capital: "Sofia",
        latitude: 42.6977,
        longitude: 23.3219,
        iso3: "BGR"
    },
    {
        countryCode: "HR",
        countryName: "Croatia",
        callingCode: "+385",
        continent: "Europe",
        currency: "EUR",
        capital: "Zagreb",
        latitude: 45.8150,
        longitude: 15.9819,
        iso3: "HRV"
    },
    {
        countryCode: "CY",
        countryName: "Cyprus",
        callingCode: "+357",
        continent: "Europe",
        currency: "EUR",
        capital: "Nicosia",
        latitude: 35.1264,
        longitude: 33.4299,
        iso3: "CYP"
    },
    {
        countryCode: "CZ",
        countryName: "Czechia",
        callingCode: "+420",
        continent: "Europe",
        currency: "CZK",
        capital: "Prague",
        latitude: 50.0755,
        longitude: 14.4378,
        iso3: "CZE"
    },
    {
        countryCode: "DK",
        countryName: "Denmark",
        callingCode: "+45",
        continent: "Europe",
        currency: "DKK",
        capital: "Copenhagen",
        latitude: 55.6761,
        longitude: 12.5683,
        iso3: "DNK"
    },
    {
        countryCode: "EE",
        countryName: "Estonia",
        callingCode: "+372",
        continent: "Europe",
        currency: "EUR",
        capital: "Tallinn",
        latitude: 59.4370,
        longitude: 24.7535,
        iso3: "EST"
    },
    {
        countryCode: "FI",
        countryName: "Finland",
        callingCode: "+358",
        continent: "Europe",
        currency: "EUR",
        capital: "Helsinki",
        latitude: 60.1695,
        longitude: 24.9354,
        iso3: "FIN"
    },
    {
        countryCode: "FR",
        countryName: "France",
        callingCode: "+33",
        continent: "Europe",
        currency: "EUR",
        capital: "Paris",
        latitude: 48.8566,
        longitude: 2.3522,
        iso3: "FRA"
    },
    {
        countryCode: "DE",
        countryName: "Germany",
        callingCode: "+49",
        continent: "Europe",
        currency: "EUR",
        capital: "Berlin",
        latitude: 52.5200,
        longitude: 13.4050,
        iso3: "DEU"
    },
    {
        countryCode: "GR",
        countryName: "Greece",
        callingCode: "+30",
        continent: "Europe",
        currency: "EUR",
        capital: "Athens",
        latitude: 37.9838,
        longitude: 23.7275,
        iso3: "GRC"
    },
    {
        countryCode: "HU",
        countryName: "Hungary",
        callingCode: "+36",
        continent: "Europe",
        currency: "HUF",
        capital: "Budapest",
        latitude: 47.4979,
        longitude: 19.0402,
        iso3: "HUN"
    },
    {
        countryCode: "IE",
        countryName: "Ireland",
        callingCode: "+353",
        continent: "Europe",
        currency: "EUR",
        capital: "Dublin",
        latitude: 53.3498,
        longitude: -6.2603,
        iso3: "IRL"
    },
    {
        countryCode: "IT",
        countryName: "Italy",
        callingCode: "+39",
        continent: "Europe",
        currency: "EUR",
        capital: "Rome",
        latitude: 41.9028,
        longitude: 12.4964,
        iso3: "ITA"
    },
    {
        countryCode: "LV",
        countryName: "Latvia",
        callingCode: "+371",
        continent: "Europe",
        currency: "EUR",
        capital: "Riga",
        latitude: 56.9496,
        longitude: 24.1052,
        iso3: "LVA"
    },
    {
        countryCode: "LT",
        countryName: "Lithuania",
        callingCode: "+370",
        continent: "Europe",
        currency: "EUR",
        capital: "Vilnius",
        latitude: 54.6872,
        longitude: 25.2797,
        iso3: "LTU"
    },
    {
        countryCode: "LU",
        countryName: "Luxembourg",
        callingCode: "+352",
        continent: "Europe",
        currency: "EUR",
        capital: "Luxembourg City",
        latitude: 49.8153,
        longitude: 6.1296,
        iso3: "LUX"
    },
    {
        countryCode: "MT",
        countryName: "Malta",
        callingCode: "+356",
        continent: "Europe",
        currency: "EUR",
        capital: "Valletta",
        latitude: 35.8989,
        longitude: 14.5146,
        iso3: "MLT"
    },
    {
        countryCode: "NL",
        countryName: "Netherlands",
        callingCode: "+31",
        continent: "Europe",
        currency: "EUR",
        capital: "Amsterdam",
        latitude: 52.3676,
        longitude: 4.9041,
        iso3: "NLD"
    },
    {
        countryCode: "PL",
        countryName: "Poland",
        callingCode: "+48",
        continent: "Europe",
        currency: "PLN",
        capital: "Warsaw",
        latitude: 52.2297,
        longitude: 21.0122,
        iso3: "POL"
    },
    {
        countryCode: "PT",
        countryName: "Portugal",
        callingCode: "+351",
        continent: "Europe",
        currency: "EUR",
        capital: "Lisbon",
        latitude: 38.7223,
        longitude: -9.1393,
        iso3: "PRT"
    },
    {
        countryCode: "RO",
        countryName: "Romania",
        callingCode: "+40",
        continent: "Europe",
        currency: "RON",
        capital: "Bucharest",
        latitude: 44.4268,
        longitude: 26.1025,
        iso3: "ROU"
    },
    {
        countryCode: "SK",
        countryName: "Slovakia",
        callingCode: "+421",
        continent: "Europe",
        currency: "EUR",
        capital: "Bratislava",
        latitude: 48.1486,
        longitude: 17.1077,
        iso3: "SVK"
    },
    {
        countryCode: "SI",
        countryName: "Slovenia",
        callingCode: "+386",
        continent: "Europe",
        currency: "EUR",
        capital: "Ljubljana",
        latitude: 46.0569,
        longitude: 14.5058,
        iso3: "SVN"
    },
    {
        countryCode: "ES",
        countryName: "Spain",
        callingCode: "+34",
        continent: "Europe",
        currency: "EUR",
        capital: "Madrid",
        latitude: 40.4168,
        longitude: -3.7038,
        iso3: "ESP"
    },
    {
        countryCode: "SE",
        countryName: "Sweden",
        callingCode: "+46",
        continent: "Europe",
        currency: "SEK",
        capital: "Stockholm",
        latitude: 59.3293,
        longitude: 18.0686,
        iso3: "SWE"
    },
    {
        countryCode: "BN",
        countryName: "Brunei Darussalam",
        callingCode: "+673",
        continent: "Asia",
        currency: "BND",
        capital: "Bandar Seri Begawan",
        latitude: 4.5353,
        longitude: 114.7277,
        iso3: "BRN"
    },
    {
        countryCode: "KH",
        countryName: "Cambodia",
        callingCode: "+855",
        continent: "Asia",
        currency: "KHR",
        capital: "Phnom Penh",
        latitude: 11.5564,
        longitude: 104.9282,
        iso3: "KHM"
    },
    {
        countryCode: "ID",
        countryName: "Indonesia",
        callingCode: "+62",
        continent: "Asia",
        currency: "IDR",
        capital: "Jakarta",
        latitude: -6.2088,
        longitude: 106.8456,
        iso3: "IDN"
    },
    {
        countryCode: "LA",
        countryName: "Laos",
        callingCode: "+856",
        continent: "Asia",
        currency: "LAK",
        capital: "Vientiane",
        latitude: 17.9696,
        longitude: 102.6153,
        iso3: "LAO"
    },
    {
        countryCode: "MY",
        countryName: "Malaysia",
        callingCode: "+60",
        continent: "Asia",
        currency: "MYR",
        capital: "Kuala Lumpur",
        latitude: 3.1390,
        longitude: 101.6869,
        iso3: "MYS"
    },
    {
        countryCode: "MM",
        countryName: "Myanmar",
        callingCode: "+95",
        continent: "Asia",
        currency: "MMK",
        capital: "Naypyidaw",
        latitude: 19.76328,
        longitude: 96.07727,
        iso3: "MMR"
    },
    {
        countryCode: "PH",
        countryName: "Philippines",
        callingCode: "+63",
        continent: "Asia",
        currency: "PHP",
        capital: "Manila",
        latitude: 14.5995,
        longitude: 120.9842,
        iso3: "PHL"
    },
    {
        countryCode: "SG",
        countryName: "Singapore",
        callingCode: "+65",
        continent: "Asia",
        currency: "SGD",
        capital: "Singapore",
        latitude: 1.3521,
        longitude: 103.8198,
        iso3: "SGP"
    },
    {
        countryCode: "TH",
        countryName: "Thailand",
        callingCode: "+66",
        continent: "Asia",
        currency: "THB",
        capital: "Bangkok",
        latitude: 13.7563,
        longitude: 100.5018,
        iso3: "THA"
    },
    {
        countryCode: "VN",
        countryName: "Vietnam",
        callingCode: "+84",
        continent: "Asia",
        currency: "VND",
        capital: "Hanoi",
        latitude: 21.0278,
        longitude: 105.8342,
        iso3: "VNM"
    },
    {
        countryCode: "BH",
        countryName: "Bahrain",
        callingCode: "+973",
        continent: "Asia",
        currency: "BHD",
        capital: "Manama",
        latitude: 26.2285,
        longitude: 50.5860,
        iso3: "BHR"
    },
    {
        countryCode: "KW",
        countryName: "Kuwait",
        callingCode: "+965",
        continent: "Asia",
        currency: "KWD",
        capital: "Kuwait City",
        latitude: 29.3117,
        longitude: 47.4818,
        iso3: "KWT"
    },
    {
        countryCode: "OM",
        countryName: "Oman",
        callingCode: "+968",
        continent: "Asia",
        currency: "OMR",
        capital: "Muscat",
        latitude: 23.5859,
        longitude: 58.4059,
        iso3: "OMN"
    },
    {
        countryCode: "QA",
        countryName: "Qatar",
        callingCode: "+974",
        continent: "Asia",
        currency: "QAR",
        capital: "Doha",
        latitude: 25.2854,
        longitude: 51.5348,
        iso3: "QAT"
    },
    {
        countryCode: "SA",
        countryName: "Saudi Arabia",
        callingCode: "+966",
        continent: "Asia",
        currency: "SAR",
        capital: "Riyadh",
        latitude: 24.7136,
        longitude: 46.6753,
        iso3: "SAU"
    },
    {
        countryCode: "AE",
        countryName: "United Arab Emirates",
        callingCode: "+971",
        continent: "Asia",
        currency: "AED",
        capital: "Abu Dhabi",
        latitude: 24.4539,
        longitude: 54.3773,
        iso3: "ARE"
    },
    {
        countryCode: "IL",
        countryName: "Israel",
        callingCode: "+972",
        continent: "Asia",
        currency: "ILS",
        capital: "Jerusalem",
        latitude: 31.77,
        longitude: 35.23,
        iso3: "ISR"
    }
];