export * from './BE-RESPONSE-FORMAT.interface';
export * from './PHONE-CONTACTs.interface';

export * from './building.interface';
export * from './complaint.interface';
export * from './country.intrerface';
export * from './default-fields.interface';
export * from './district.interface';
export * from './feature.interface';
export * from './flat.interface';
export * from './gate-entry-log.interface';
export * from './gate-pass.interface';
export * from './gates.interface';
export * from './ui/location-result .interface';
export * from './menu.interface';
export * from './notification.interface';
export * from './parking.interface';
export * from './payment.interface';
export * from './role-menu.interface';
export * from './role.interface';
export * from './society-feature.interface';
export * from './society.interface';
export * from './state.interface';
export * from './ui/ui-control-config.interface';
export * from './ui/ui-drop-down-option.interface';
export * from './user-roles';
export * from './user.interface';
export * from './vehicle.interface';